import 'dotenv/config';

import { readFileSync } from 'fs';
import path from 'path';

import express from 'express';
import swaggerUi from 'swagger-ui-express';

import { initDatabase } from './db/init';
import apiRoutes from './routes';

// swagger_output.json is generated by `npm run swagger` and lives outside src/
// so it is read at runtime rather than bundled as a TypeScript import.
const swaggerFile: object = JSON.parse(
  readFileSync(path.join(__dirname, '../swagger/output.json'), 'utf-8'),
);

const app = express();
const PORT = Number(process.env.PORT ?? 3001);

app.use(express.json());
app.use('/api/docs', swaggerUi.serve, swaggerUi.setup(swaggerFile));
app.use('/api', apiRoutes);

/**
 * Initializes the database before accepting requests, ensuring all tables
 * exist by the time the first connection arrives.
 */
async function start(): Promise<void> {
  await initDatabase();
  app.listen(PORT, () => {
    console.log(`[server] Running on http://localhost:${PORT}`);
  });
}

// Catch startup failures explicitly so the process exits with a non-zero
// code instead of hanging with an unhandled rejection warning.
start().catch(err => {
  console.error('[server] Failed to start:', err);
  process.exit(1);
});
