import 'dotenv/config';

import { readFileSync } from 'fs';
import path from 'path';

import express from 'express';
import swaggerUi from 'swagger-ui-express';

import { initDatabase } from './db/init';
import { createLogger } from './logger';
import { errorHandler } from './middleware/errorHandler';
import { UPLOADS_DIR } from './middleware/upload';
import apiRoutes from './routes';
import { startAutoBackupScheduler } from './scheduler/autoBackupScheduler';

const logger = createLogger('server');

// swagger_output.json is generated by `npm run swagger` and lives outside src/
// so it is read at runtime rather than bundled as a TypeScript import.
const swaggerFile: object = JSON.parse(
  readFileSync(path.join(__dirname, '../swagger/output.json'), 'utf-8'),
);

const app = express();
const PORT = Number(process.env.VITE_API_PORT ?? 3001);

// Cross-origin requests only matter when the frontend calls this API
// directly instead of through its own nginx same-origin proxy (e.g. when
// VITE_API_DOMAIN points at a separate public API domain); CORS_ORIGIN opts
// specific origins into that access, comma-separated for multiple domains.
const CORS_ORIGINS = (process.env.CORS_ORIGIN ?? '')
  .split(',')
  .map(origin => origin.trim())
  .filter(Boolean);

if (CORS_ORIGINS.length > 0) {
  app.use((req, res, next) => {
    const origin = req.headers.origin;
    if (origin && CORS_ORIGINS.includes(origin)) {
      res.setHeader('Access-Control-Allow-Origin', origin);
      res.setHeader('Vary', 'Origin');
    }
    res.setHeader(
      'Access-Control-Allow-Methods',
      'GET, POST, PUT, PATCH, DELETE, OPTIONS',
    );
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    if (req.method === 'OPTIONS') {
      res.sendStatus(204);
      return;
    }
    next();
  });
}

app.use(express.json());

// Lightweight request log: one INFO line per response, after it's sent, so
// duration reflects the full request/response cycle.
app.use((req, res, next) => {
  const startedAt = Date.now();
  res.on('finish', () => {
    logger.info('Request handled', {
      method: req.method,
      path: req.originalUrl,
      status: res.statusCode,
      durationMs: Date.now() - startedAt,
    });
  });
  next();
});

app.use('/uploads', express.static(UPLOADS_DIR));
app.use('/api/docs', swaggerUi.serve, swaggerUi.setup(swaggerFile));
app.use('/api', apiRoutes);

// Must be registered after every route/middleware above: Express identifies
// an error handler purely by its 4-argument signature.
app.use(errorHandler);

/**
 * Initializes the database before accepting requests, ensuring all tables
 * exist by the time the first connection arrives.
 */
async function start(): Promise<void> {
  await initDatabase();
  startAutoBackupScheduler();
  app.listen(PORT, () => {
    logger.info('Server started', { port: PORT });
  });
}

// Catch startup failures explicitly so the process exits with a non-zero
// code instead of hanging with an unhandled rejection warning.
start().catch(err => {
  logger.error('Server failed to start', undefined, err);
  process.exit(1);
});
